trigger: none

jobs:
  - template: ../../eng/pipelines/templates/jobs/archetype-sdk-tests.yml
    parameters:
      BuildTargetingString: azure-data-tables
      ServiceDirectory: tables
      EnvVars:
        TEST_MODE: 'RunLiveNoRecord'
        AZURE_SKIP_LIVE_RECORDING: 'True'
        AZURE_TEST_RUN_LIVE: 'true'
        AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id)
        AZURE_SUBSCRIPTION_ID: $(azure-subscription-id)
        AZURE_CLIENT_SECRET: $(aad-azure-sdk-test-client-secret)
        AZURE_CLIENT_ID: $(aad-azure-sdk-test-client-id)
